name: Deploy Bridge Explorer to Staging

on:
  push:
    branches:
      - dev
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Deploy
        uses: reggionick/s3-deploy@v3
        with:
          folder: build
          bucket: ${{ secrets.DEV_S3_BUCKET }}
          bucket-region: ${{ secrets.DEV_S3_BUCKET_REGION }}
          invalidation: /
          delete-removed: true
          no-cache: true
          private: false
